#pragma once

#include <stdint.h>

#define FIRMWARE_VERSION_MAJOR  0u
#define FIRMWARE_VERSION_MINOR  7u
#define FIRMWARE_VERSION_PATCH  0u

#define FIRMWARE_VERSION_STRING "0.7.0"
#define FIRMWARE_VERSION_U32 \
    ((uint32_t)((FIRMWARE_VERSION_MAJOR << 16) | (FIRMWARE_VERSION_MINOR << 8) | FIRMWARE_VERSION_PATCH))
